[package]
name = "bpdaggen"
version = "0.1.0"
authors = ["Fred Morcos <fred.morcos@gmail.com>"]
edition = "2018"
description = "Generate random bipartite DAGs"

[dependencies]
rand = "=0.7.0"
log = "=0.4.6"
env_logger = "=0.6.2"
structopt = "=0.2.18"
