[package]
name = "gstats"
version = "0.1.0"
authors = ["Fred Morcos <fred.morcos@gmail.com>"]
edition = "2018"

[dependencies]
log = "=0.4.6"
env_logger = "=0.6.2"
structopt = "=0.2.18"
conv = "=0.3.3"
